export const breadcrumbAwardeeData = [
  {
    name: 'Home',
    link: '/',
  },
  {
    name: 'Awardee',
    link: '/admin/awardee',
  },
];
export const awardeeData = [
  {
    id: 1,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  // create 9 dummy data here
  {
    id: 2,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 3,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 4,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 5,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 6,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 7,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 8,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 9,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
  {
    id: 10,
    name: 'John Doe',
    department: 'Executive',
    division: '',
    position: 'CEO',
    prodi: 'Pendidikan Management',
    year: '2020',
    photo: '/images/avatar.jpeg',
  },
];
